#!/usr/bin/env python3
"""Bundle one module tree into a single review file: brief, YAML manifest with
source refs, line numbered verbatim code. Built for chat reviewers that have no
repo access. Deterministic output.

Usage:
  python3 scripts/bundle_review.py                     # mcp/jev/grep + its tests
  python3 scripts/bundle_review.py --no-tests
  python3 scripts/bundle_review.py --upstream /tmp/jevgrep-src/src
"""
import argparse
import hashlib
import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

DEFAULT_MODULE = os.path.join("mcp", "jev", "grep")
DEFAULT_TESTS_GLOB = "tests/test_jevgrep_*.py"
DEFAULT_OUT = os.path.join("tmp", "review", "jevgrep-review-bundle.md")

# Reviewer questions point at upstream names; parity review needs them in scope.
UPSTREAM_FILES = ["contracts.ts", "engine.ts", "response/render.ts", "evaluation/jev.ts"]

BRIEF = """\
# JevGrep Python port: code review bundle

Generated by scripts/bundle_review.py. One file, line numbered, verbatim. Cite
findings as path:line from the numbered listings below.

## What you are reviewing

`mcp/jev/grep` is a Python port of JevGrep v0.1.0 by Nassim Arifette (TypeScript,
https://github.com/nassim-arifette/jevgrep, MIT). Scope is the search engine plus
the stdio MCP server. The port keeps the upstream response contract
(schema_version "1") and its validator invariants. Runtime is Python 3.10+,
standard library only, with one internal dependency: `sage.jev.config.yaml_lite` parses
the YAML trusted profile.

Pipeline:

    request --> contracts.parse
            --> prepare: inventory --> snapshot --> chunk
            --> cache lookup --> plan: batches, scan caps
            --> evaluate: provider, bounded retries
            --> freshness check --> select under budget --> render measured
            --> validate --> outcome JSON

## What must stay true

- A rejected request dispatches nothing. Early failures return bounded error
  outcomes, never exceptions.
- A provider failure is never a score. A missing, duplicated, wrong typed,
  non finite or out of range answer is an unavailable evaluation, not a zero.
- Missing usage stays unknown. Usage counters keep their partition identities:
  evaluated equals below plus above threshold, above threshold equals
  represented plus budget omitted plus stale, and so on in validate_search_result.
- Every excerpt is an exact snapshot slice carrying path, line range and file
  hash. Nothing is truncated, rewritten or regenerated.
- The mandatory report envelope is reserved before any paid work. Ranges are
  removed lowest priority first until the measured payload fits the budget.
- Authorization pins one repository root. Links inside the root are refused.
  The trusted profile and the score cache live outside the repository.
  Credential patterns quarantine a whole file before any dispatch.
- One provider attempt per scheduler dispatch. No redirect following, bounded
  response bodies, duplicate JSON keys in answers invalidate that answer.
- MCP runs one active search and one queued search, then answers BUSY. A
  cancelled call never emits a later result.

## Accepted divergences from upstream

Full ledger in the NOTICE file. Summary: local token estimator
`utf8-bytes@1/ceil-4` instead of tiktoken cl100k_base; line window chunking only,
the TypeScript syntax chunker is gone; the Vercel gateway adapter speaks raw HTTP;
Windows reparse checks simplified and symlinked ancestors above the root are
tolerated; YAML profile instead of JSON. Do not report these as defects. Report
them only when implemented wrong or when a safety property upstream had is lost.

## Review questions

1. Contract parity. `contracts.py` validate_search_result and `render.py` against
   the upstream rules in contracts.ts and response/render.ts. Hunt for an
   invariant that is missing, weakened or mistranslated.
2. Engine accounting. `engine.py` cache identity inputs, usage reservation logic,
   plan and cap handling, stop reasons, the freshness loop. The failure shapes to
   hunt are off by one, silent zero and double counted reservations.
3. Provider layer. `jev.py`, `openrouter.py`, `vercel_gateway.py`, `http.py`. One
   attempt per call, no redirect following, bounded bodies, duplicate key
   detection, status classification that never reads an error body.
4. Security. `prepare.py` credential quarantine, `ignore_rules.py` semantics,
   `authorization.py` containment, secret handling in `config.py` and the CLI.
5. Concurrency. `scheduler.py` thread pool and `mcp_server.py` queue, BUSY and
   cancellation. A race that emits after cancellation counts as high.
6. Porting bugs. Any mistranslated branch, dead code or Python semantic shift
   that changes behavior.

For every finding give severity, path:line, what upstream does and why it
matters. End with the single fix you would make first.
"""


def collect_files(module_dir, with_tests, upstream_root):
    paths = []
    for name in sorted(os.listdir(module_dir)):
        full = os.path.join(module_dir, name)
        if os.path.isfile(full) and (name.endswith(".py") or name == "NOTICE"):
            paths.append(full)
    if with_tests:
        import glob
        paths.extend(sorted(glob.glob(os.path.join(REPO_ROOT, DEFAULT_TESTS_GLOB))))
    if upstream_root:
        for name in UPSTREAM_FILES:
            full = os.path.join(upstream_root, name)
            if os.path.isfile(full):
                paths.append(full)
    return paths


def manifest_block(paths):
    lines = ["## Manifest", "", "```yaml", "manifest:"]
    for path in paths:
        with open(path, "rb") as handle:
            data = handle.read()
        text = data.decode("utf-8")
        lines.append(f"  - path: {_yaml_scalar(_relative(path))}")
        lines.append(f"    role: {_yaml_scalar(_role(path))}")
        lines.append(f"    lines: {len(text.splitlines())}")
        lines.append(f"    sha256: {hashlib.sha256(data).hexdigest()}")
    lines.append("```")
    lines.append("")
    return "\n".join(lines)


def _relative(path):
    if path.startswith(REPO_ROOT + os.sep):
        return os.path.relpath(path, REPO_ROOT)
    return path


def _role(path):
    name = os.path.basename(path)
    if name == "NOTICE":
        return "license and divergence ledger"
    if name.endswith(".ts"):
        return "upstream reference for parity review"
    if name.startswith("test_"):
        return "offline test expectations"
    return "port source"


def _yaml_scalar(text):
    return text if all(character.isalnum() or character in "./_- " for character in text) else f'"{text}"'


def listing_block(path):
    with open(path, "r", encoding="utf-8") as handle:
        text = handle.read()
    relative = _relative(path)
    body = "\n".join(f"{number:5d} | {line}"
                     for number, line in enumerate(text.splitlines(), start=1))
    return f"===== FILE: {relative} ({len(text.splitlines())} lines) =====\n\n{body}\n"


def main(argv=None):
    parser = argparse.ArgumentParser(description="bundle one module tree into a single review file")
    parser.add_argument("--module", default=DEFAULT_MODULE)
    parser.add_argument("--no-tests", action="store_true")
    parser.add_argument("--upstream", help="directory of upstream src for parity review")
    parser.add_argument("--out", default=DEFAULT_OUT)
    args = parser.parse_args(argv)

    module_dir = args.module if os.path.isabs(args.module) else os.path.join(REPO_ROOT, args.module)
    paths = collect_files(module_dir, not args.no_tests, args.upstream)
    if not paths:
        print("no files collected", file=sys.stderr)
        return 2

    parts = [BRIEF, manifest_block(paths)]
    parts.extend(listing_block(path) for path in paths)
    bundle = "\n".join(parts)

    out = args.out if os.path.isabs(args.out) else os.path.join(REPO_ROOT, args.out)
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8") as handle:
        handle.write(bundle)

    total_lines = sum(1 for _ in bundle.splitlines())
    print(f"wrote {out}")
    print(f"files: {len(paths)}  lines: {total_lines}  bytes: {len(bundle.encode('utf-8'))}  "
          f"est_tokens: {len(bundle.encode('utf-8')) // 4}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
